[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_FORMSPREE_ID = "xwvnyqzz"
  VITE_PHONE = "+48578224721"
  VITE_EMAIL = "mbarmobilny@gmail.com"
  VITE_INSTAGRAM_URL = "https://www.instagram.com/mbarmobilny?igsh=MWp4NXZtNG91cm92ZA=="
  VITE_FACEBOOK_URL = "https://www.facebook.com/share/17HJkD8LRt/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
